### PR TITLE
Show task to myself

### PR DESCRIPTION
**Pull request by firewalker06**
Sometimes we forgot which task that someone assigned to us :confused: and tired of looking at dozens of iceboxes :icecream:

### CODE REVIEW

**Comment by balvig** [comment]
Hello @firewalker06! Thanks for contributing, I've actually had this on my "todo list" for quite some time :sweat_smile:  

I've however been thinking of allowing us to set the filters _directly_ (ie `git start --filter=....`) instead of having to make a new option (ie `include-icebox`, `only-me` etc) everytime, what do you think? :smile:

**Comment by firewalker06** [comment]
Using `--filter` directly is better (more control). But having a set of option seems fine, too. Otherwise you need to put your name on the filter everytime, for example: `git start --filter=owned_by:Didik` :grin:

**Comment by balvig** [comment]
Good point, I'll have a think about it! :+1:

**Comment by balvig** [comment]
@firewalker06 sorry for the wait :bow: 
Please take a look at #38, `2.6.0` and `git start --filter=me` should hopefully do the trick!

**Pull request closed without merging**
